### ISSUE TITLE
Rsocrata and read.socrata issues

### ISSUE THREAD

**Issue by finestjava** [Chicago/RSocrata#164] opened 2019-03-15 20:47 UTC
Good Afternoon Socratists

My RSocrata snippets all stopped working about a week ago.
Just checking in, to see if I missed something. 

ord.01.ytd.s <- read.socrata("https://data.cityofchicago.org/resource/6zsd-86xi.json",
app_token = "fakeToken", email = "bigdata@1537news.com", 
password = "fakePassword",stringsAsFactors = FALSE)

Here is the error code - 
Error in curl::curl_fetch_memory(url, handle = handle) : 

The only way I can download this data is from the web, 
with a totally different ColNames structure.

Thanks
Harry

**Comment by geneorama** [comment] 2019-03-15 21:11
I think the problem is that you're running out of memory.  The crimes data set is very large and growing daily.  So perhaps it just hit a point where it got too big for memory.

I would suggest subsetting by a field such as `updated_on`.  For example:

```
dat <- read.socrata("https://data.cityofchicago.org/resource/6zsd-86xi.json?$where=updated_on>'2019-03-01'",
                    stringsAsFactors = FALSE)
```

if you wanted to download just the past 10 days you could do something like this:
```
q <- sprintf("https://data.cityofchicago.org/resource/6zsd-86xi.json?$where=updated_on>'%s'",
             Sys.Date() - 10)
dat <- read.socrata(q, stringsAsFactors = FALSE)
```

**Comment by geneorama** [comment] 2019-03-15 21:26
Also, I wanted to mention that the field names (and field order) are different depending on if you download as JSON or CSV.

**Comment by finestjava** [comment] 2019-03-15 21:30
geneorama- I have downloading this data since 2009 - took it while but these 1.6GB files always came through. It was as my interests got more involved R came into the picture. Fun software.
Any how, within the last few months have been changing things around to include R in my workflow and have created quite a few snippets/templates/functions that allow me to do my most common tasks. Just a;ll that stopped working as I mentioned about a week ago.

Your idea of sub-setting is good sense especially thanks for the url example. I will def give that a try as the clumsiness of the filter options are truly tedious. I have been doing all changes post download.

In closing, I appreciate what i have learned here but also suspect there is more to the real solution of why everything changed in my world a week ago.

Thanks again geneorama

**Comment by geneorama** [comment] 2019-03-15 21:30
@finestjava I'm closing for now, please let me know if we should reopen.

**Closed by geneorama** 2019-03-15 21:30 UTC

**Comment by geneorama** [comment] 2019-03-15 21:39
@finestjava glad I could help.

I hadn't seen your reply when I closed the issue, our messages were crossed.  Regarding this part:

> In closing, I appreciate what i have learned here but also suspect there is more to the real solution of why everything changed in my world a week ago.

If you find something else that I can reproduce, let me know. I wouldn't be surprised if you saw performance changes depending on which version of R and the curl packages you're using. It might help to download the latest R and do `update.packages()` every once in a while.

**Comment by finestjava** [comment] 2019-04-02 18:09
Hi Gene,

Getting a bad Request from this search based on your suggestions.
This is searching the Taxi Rides dataset

dat <- read.socrata(
  "https://data.cityofchicago.org/resource/wrvz-psew.csv?where=Trip.Start.Timestamp>'2016-12-31’"

thank in advance
Harry

**Comment by tomschenkjr** [comment] 2019-04-02 18:24
@finestjava - the `Trip.Start.Timestamp` field is a date/time field, so you'll need to specify the full timestamp, e.g., `2014-10-21T19:45:00.000`

**Comment by geneorama** [comment] 2019-04-02 20:54
@tomschenkjr - Thank you! I didn't know that the timestamp columns require a timestamp for comparison in the queries, so your response saved me a lot of investigation.

@finestjava Right now there is an [issue](http://dev.cityofchicago.org/open%20data/data%20portal/2017/10/24/taxi-data-behind.html) with the taxi data (which is hopefully on the brink of being resolved), so I modified the example for some dates that work. 

```
tm <- strftime(as.POSIXct("2017-07-30"), 
               format = "%Y-%m-%dT%H:%M:%S", 
               usetz = FALSE)
q <- sprintf("https://data.cityofchicago.org/resource/wrvz-psew.json?$where=trip_start_timestamp>'%s'",
             tm)
dat <- read.socrata(q, stringsAsFactors = FALSE)
```

As you can see, it's a bit of an ordeal to get R to spit things out in a nice ISO8601 format. 

The curious thing is I couldn't get the date comparison to work for the .csv resource, or using `Trip.Start.Timestamp`. I believe you might need to use the JSON names and data source for constructing the queries.

**Comment by finestjava** [comment] 2019-04-05 20:49
Hi,

Getting a bad Request from this search based on your search format suggestions.
This is searching the Taxi Rides dataset

I tried filtering on the web but mostly got spinning wheel waiting-
Downloaded the whole file but even IBM Watson and Google Drive could not handle the size of the file
43GB file with 112M records.

Also the dataset is listed as 2013 - present, I only could see that somewhere in 2017 the records stopped.

If I could get some additional help with a soSql filter scheme that will work would be great

dat <- read.socrata(
 "https://data.cityofchicago.org/resource/wrvz-psew.csv?where=Trip.Start.Timestamp <https://data.cityofchicago.org/resource/wrvz-psew.csv?where=Trip.Start.Timestamp>>'2016-12-31’”


thank in advance
Harry

**Comment by geneorama** [comment] 2019-04-05 21:03
You've got a few errors in your request, try this: `https://data.cityofchicago.org/resource/wrvz-psew.csv?&$where=trip_start_timestamp>'2016-12-31'`

You can test your request in the browser (i.e. chrome) to see if the request is valid.

Here's a link to the filtering documentation: https://dev.socrata.com/docs/filtering.html

**Comment by geneorama** [comment] 2019-04-05 21:50
@finestjava My apologies, I had something in my query that Socrata would accept, but caused an error in RSocrata.

Please try **this**: `https://data.cityofchicago.org/resource/wrvz-psew.csv?$where=trip_start_timestamp>'2016-12-31'`

I tested it in RSocrata: `read.socrata("https://data.cityofchicago.org/resource/wrvz-psew.csv?$where=trip_start_timestamp>'2016-12-31'")`

**Comment by geneorama** [comment] 2019-04-05 21:58
@finestjava 

Please see my previous response regarding the limitations of the taxi dataset:

> @finestjava Right now there is an issue with the taxi data (which is hopefully on the brink of being resolved), so I modified the example for some dates that work.
http://dev.cityofchicago.org/open%20data/data%20portal/2017/10/24/taxi-data-behind.html
