### ISSUE TITLE
return: text/plain not a supported file format, I am not sure if there is syntax error or what

### ISSUE THREAD

**Issue by LoveYukee** [Chicago/RSocrata#172] opened 2019-05-23 01:40 UTC
library(dplyr)
#library(ggplot2)
#library(leaflet)
library(soql)
library(RSocrata)
library(magrittr)

api_url <- "https://openpaymentsdata.cms.gov/resource/tvyk-kca8.csv"

query <- soql() %>% 
  soql_add_endpoint(api_url) %>%
  soql_limit(2000) %>%
  soql_select(paste(
    "teaching_hospital_name", 
    "physician_primary_type", 
    "physician_specialty", 
    "recipient_zip_code", 
    "total_amount_of_payment_usdollars", 
    "submitting_applicable_manufacturer_or_applicable_gpo_name", 
    "date_of_payment", 
    "recipient_state", 
    sep = ","
  )) %>%
  soql_order("date_of_payment", desc=TRUE) 

api_url2004 <- "https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv$$app_token = Wukqis8FG8q4nscOFapsQrm1V"
query1 <- soql() %>%
  soql_add_endpoint(api_url2004) %>%
  soql_limit(2000)
data <- read.socrata(query1,"Wukqis8FG8q4nscOFapsQrm1V")

stringQuery = "physician_last_name LIKE 'NAZARIAN'"
api_url <- "https://openpaymentsdata.cms.gov/resource/ak56-dpcz.csv$$Wukqis8FG8q4nscOFapsQrm1V"
stringQuery = "physician_last_name LIKE 'Nazarian' AND UPPER(physician_first_name) LIKE 'SAMAN'"
stringQuery1 = "upper(physician_last_name) ='BERGER' AND upper(physician_first_name) ='RONALD' 
AND starts_with(UPPER(physician_middle_name),'D')"
query1 = soql() %>% 
  soql_add_endpoint(api_url) %>%
  soql_select("Physician_Profile_ID") %>%
  soql_where(stringQuery1) %>%
  soql_order("date_of_payment", desc=TRUE) %>%
  as.character()
data <- read.socrata(query1,"Wukqis8FG8q4nscOFapsQrm1V")

**Comment by geneorama** [comment] 2019-05-23 01:43
Can you try just using read.table or data.table’s fread?

(Or readLines if all else fails)

On May 22, 2019, at 8:40 PM, LoveYukee <notifications@github.com<mailto:notifications@github.com>> wrote:


library(dplyr)
#library(ggplot2)
#library(leaflet)
library(soql)
library(RSocrata)
library(magrittr)

api_url <- "https://openpaymentsdata.cms.gov/resource/tvyk-kca8.csv"

query <- soql() %>%
soql_add_endpoint(api_url) %>%
soql_limit(2000) %>%
soql_select(paste(
"teaching_hospital_name",
"physician_primary_type",
"physician_specialty",
"recipient_zip_code",
"total_amount_of_payment_usdollars",
"submitting_applicable_manufacturer_or_applicable_gpo_name",
"date_of_payment",
"recipient_state",
sep = ","
)) %>%
soql_order("date_of_payment", desc=TRUE)

api_url2004 <- "https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv$$app_token = Wukqis8FG8q4nscOFapsQrm1V"
query1 <- soql() %>%
soql_add_endpoint(api_url2004) %>%
soql_limit(2000)
data <- read.socrata(query1,"Wukqis8FG8q4nscOFapsQrm1V")

stringQuery = "physician_last_name LIKE 'NAZARIAN'"
api_url <- "https://openpaymentsdata.cms.gov/resource/ak56-dpcz.csv$$Wukqis8FG8q4nscOFapsQrm1V"
stringQuery = "physician_last_name LIKE 'Nazarian' AND UPPER(physician_first_name) LIKE 'SAMAN'"
stringQuery1 = "upper(physician_last_name) ='BERGER' AND upper(physician_first_name) ='RONALD'
AND starts_with(UPPER(physician_middle_name),'D')"
query1 = soql() %>%
soql_add_endpoint(api_url) %>%
soql_select("Physician_Profile_ID") %>%
soql_where(stringQuery1) %>%
soql_order("date_of_payment", desc=TRUE) %>%
as.character()
data <- read.socrata(query1,"Wukqis8FG8q4nscOFapsQrm1V")

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/url?k=2684ac34-7a15575c-2684785c-0cc47ad32322-0343f759172a7af0&q=1&u=https%3A%2F%2Fgithub.com%2FChicago%2FRSocrata%2Fissues%2F172%3Femail_source%3Dnotifications%26email_token%3DAAKT3RC76KYRMPW2UEJBMV3PWXYXZA5CNFSM4HOZHEBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GVK6TZQ>, or mute the thread<https://protect2.fireeye.com/url?k=b80aabca-e49b50a2-b80a7fa2-0cc47ad32322-d82fcb8b5e09d77a&q=1&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAKT3RGAI5GJYI3BSBGUIDDPWXYXZANCNFSM4HOZHEBA>.


________________________________
This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. If you are not the intended recipient of this e-mail (or the person responsible for delivering this document to the intended recipient), you are hereby notified that any dissemination, distribution, printing or copying of this e-mail, and any attachment thereto, is strictly prohibited. If you have received this e-mail in error, please respond to the individual sending the message, and permanently delete the original and any copy of any e-mail and printout thereof.

**Comment by LoveYukee** [comment] 2019-05-23 01:49
Hi, thanks for you suggestion, but it is the first the time that I used this package, could you please explain a little bit? Thank you so much

**Comment by geneorama** [comment] 2019-05-23 01:54
I think read socrata only works for getting full data sets, or simple queries that filter rows or columns.

I’m just not at a computer to test and confirm.

On May 22, 2019, at 8:49 PM, LoveYukee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, thanks for you suggestion, but it is the first the time that I used this package, could you please explain a little bit? Thank you so much

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/url?k=eab81c3f-b62a2693-eab8c857-0cc47ad9c05e-c01a2b4994a0e2f3&q=1&u=https%3A%2F%2Fgithub.com%2FChicago%2FRSocrata%2Fissues%2F172%3Femail_source%3Dnotifications%26email_token%3DAAKT3RCNSLFX7CJYSUWSBETPWXZ3ZA5CNFSM4HOZHEBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWA2S2A%23issuecomment-495036776>, or mute the thread<https://protect2.fireeye.com/url?k=7abcefc9-262ed565-7abc3ba1-0cc47ad9c05e-fb93eaa845e64611&q=1&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAKT3RBTBAOT2YZNQEN4RGLPWXZ3ZANCNFSM4HOZHEBA>.


________________________________
This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. If you are not the intended recipient of this e-mail (or the person responsible for delivering this document to the intended recipient), you are hereby notified that any dissemination, distribution, printing or copying of this e-mail, and any attachment thereto, is strictly prohibited. If you have received this e-mail in error, please respond to the individual sending the message, and permanently delete the original and any copy of any e-mail and printout thereof.

**Comment by LoveYukee** [comment] 2019-05-23 01:55
Thank you, I will try

**Comment by geneorama** [comment] 2019-05-23 14:18
Not sure what all is going on with your code... 

First, it appears that `query` is not used anywhere, so the reproducible part of your code is just this:
```
library(dplyr)
library(soql)
library(RSocrata)
api_url2004 <- "https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv$$app_token = Wukqis8FG8q4nscOFapsQrm1V"
query1 <- soql() %>%
    soql_add_endpoint(api_url2004) %>%
    soql_limit(2000)
data <- read.socrata(query1,"Wukqis8FG8q4nscOFapsQrm1V")
```

If you look at `query1`, I think it's malformed (missing a `?`).  I think this `https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv$$app_token = Wukqis8FG8q4nscOFapsQrm1V?$limit=2000` should be this `https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv?$$app_token = Wukqis8FG8q4nscOFapsQrm1V&$limit=2000`

However, I can't test it because I can't access the resource without authentication.

I would take out the token, and the limit and do this:
```
data <- read.socrata(url = "https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv",
                     email = "you@example.com",
                     password = "yourpassword",
                     app_token = NULL,
                     stringsAsFactors = FALSE)
```

You don't need the last two lines, but when I'm troubleshooting I like to put everything in the function, named, just to be careful.

If you don't want to put your password in plain text in your script, I would suggest using something like this:
```
data <- read.socrata(url = "https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv",
                     email = yaml::read_yaml("credentials.yaml")$email,
                     password = yaml::read_yaml("credentials.yaml")$password,
                     app_token = NULL,
                     stringsAsFactors = FALSE)
```

Where the credential file has your email and password. There are probably fancier solutions, but at least you don't need to commit your code.

I thought you were experiencing a different issue.  If you are doing an aggregation then `read.socrata` can have issues.  I just documented that with #173

**Comment by LoveYukee** [comment] 2019-05-27 23:53
hi, actually I tried in both ways but all failed, the bug in title did not occur but get a 403 error
`> api_url2004 <- "https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv?$$app_token = qkq8v5ZBNzxC5IjatPbYSeCm1"
> query <- soql() %>%
+   soql_add_endpoint(api_url2004) %>%
+   soql_limit(2000)
> token <- "qkq8v5ZBNzxC5IjatPbYSeCm1"
> data <- read.socrata(query, token)
2019-05-27 18:15:59.204 getResponse: Error in httr GET: 403  https://openpaymentsdata.cms.gov/resource/gysc-m9qm.csv?%24%24app_token%20=%20qkq8v5ZBNzxC5IjatPbYSeCm1%3F%24limit%3D2000&%24%24app_token=qkq8v5ZBNzxC5IjatPbYSeCm1&$order=:id  You must be logged in to access this resource
Error in getResponse(validUrl, email, password) : Forbidden (HTTP 403).`

I am not sure if my app token created in RSocrata is valid right now because when I copy paste this url, I could not access the data.

**Comment by LoveYukee** [comment] 2019-05-27 23:55
I am pretty sure that the query needs to be included

**Comment by LoveYukee** [comment] 2019-05-28 00:14
I am sorry but the code in last row is data <- read.socrata(query, app_token = token)
but it still returns the same error (forbidden 403)

**Comment by tomschenkjr** [comment] 2019-05-29 04:12
@LoveYukee - I think this [may be the same issue](https://stackoverflow.com/questions/56334505/my-app-token-is-useless-how-could-i-access-to-the-dataset), but will refer you over to [my StackOverflow response](https://stackoverflow.com/questions/56334505/my-app-token-is-useless-how-could-i-access-to-the-dataset/56352795#56352795) since others may also find it.

Going to close the issue for now since it seems to be related to a private data set. Feel free to respond over in StackOverflow. We can reopen this issue if there is a bug with the package.

Thanks!

**Closed by tomschenkjr** 2019-05-29 04:12 UTC
