### ISSUE TITLE
write.socrata creates blank columns

### ISSUE THREAD

**Issue by chursaner** [Chicago/RSocrata#152] opened 2018-02-14 00:12 UTC
For the City of LA, I have a script to read from the google analytics API and write to a dataset on data.lacity.org. However, the write.socrata API creates some blank columns. This has happened to me in the past before. Seems to be an issue with numeric data types, since the Data column wrote correctly. 

I've attached/pasted some screenshots and an excel doc of the dataset. The dataset on the open data portal is [here](https://data.lacity.org/A-Well-Run-City/Open-Data-Site-Traffic/d4kt-8j3n).

**Data types in socrata**
<img width="1111" alt="data types in socrata" src="https://user-images.githubusercontent.com/17167667/36181189-9f06bd10-10d8-11e8-8276-6443b558f786.png">
**Data types in r (matches)**
<img width="702" alt="data types in r" src="https://user-images.githubusercontent.com/17167667/36181190-9f2db6a4-10d8-11e8-9e93-58cd0dfd5eb9.png">

**Write.socrata confirmation message**
<img width="482" alt="write socr
[open_data_traffic.xlsx](https://github.com/Chicago/RSocrata/files/1722189/open_data_traffic.xlsx)
ata message" src="https://user-images.githubusercontent.com/17167667/36181170-85dc6664-10d8-11e8-8048-526c96c15cb2.png">
**Blank columns**
<img width="1139" alt="blank columns" src="https://user-images.githubusercontent.com/17167667/36181171-85ffc99c-10d8-11e8-8fe0-aa44fbb094e4.png">

[open_data_traffic.xlsx](https://github.com/Chicago/RSocrata/files/1722192/open_data_traffic.xlsx)

**Comment by tomschenkjr** [comment] 2018-02-15 18:31
Thanks for the details behind the issue. It really helped being able to reproduce the issue and pinpoint a resolution. We've identified the problem and think there is a fix.

This problem arose from two circumstances. First, this data set has a number of partially blank rows for the geohub columns (presumably this is before Geohub). When preparing the dataset for upload, it is converted to JSON. However, if the column is blank, R does not create a field in the JSON. That is, a JSON field is only created with non-null entries. This can create upload situations where the number of fields/columns differ per entry/row.

Second, the names in your R workspace also don't appear to line-up to the API field names. For instance, the second field in your R workspace is `users.socrata`, but the API field name on the portal is `socrata_users`.

In combination, Socrata is unable to determine how to handle an uneven number of fields/columns per entry/row since the names do not align. `Date` appears correctly because the R names align with the Socrata API field names.

## Resolution

There are two potential solutions. First, you can change the names in your R workspace as part of the workflow to align it to the API names. That is

```r
names(data) <- c("date", "socrata_users", 
                   "socrata_sessions", "socrata_bounce_rate", 
                   "geohub_users", "geohub_sessions", 
                   "geohub_bounce_rate", "combined_users")
```
before executing `write.socrata()`. I tested this and it appeared to work.

Alternatively, you can replace `NA` in your dataframe with `""`. R will convert this to a blank string, which is handled appropriately on the upload. I have not tested this, but seems like it would work.

I will close the issue for now as likely resolved. However, if you have further questions or this doesn't fully resolve the problem, just reply back to this thread so we can get back to you.

**Closed by tomschenkjr** 2018-02-15 18:31 UTC
Labels: bug

**Comment by chursaner** [comment] 2018-02-27 23:50
A little delayed, but excellent!! That worked. Thanks Tom
